version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./cyfuture.db
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=production
    volumes:
      - ./cyfuture.db:/app/cyfuture.db
      - ./uploaded_invoices:/app/uploaded_invoices
    depends_on:
      - frontend

  frontend:
    build:
      context: ./fiscal-flow-ai-suite-main
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_APP_NAME=Cyfuture Fiscal Flow
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend 